#! /bin/bash
#
# make sure env variable is defined eg - JREBEL_HOME=$HOME/bin/jrebel
#
#  -Drebel.log=true \
#

#
# current version
#
java \
  -agentpath:$JREBEL_HOME/lib/libjrebel64.dylib \
  -Xmx1024M \
  -XX:ReservedCodeCacheSize=48m \
  -Xss2M \
  -XX:MaxPermSize=512m \
  -XX:+CMSClassUnloadingEnabled \
  -jar `dirname $0`/sbt-launch-0.13.8.jar "$@"
